### ISSUE TITLE
native bindings

### ISSUE THREAD

**Issue by omares** [pksunkara/inflect#1]
The current native bindings implementation does not allow to pass parameters to the inflect methods because of the inner workings of `prototype.__defineGetter__`. Thus calling `"example_string".camelize(false)` results in an error.

I could provide a fix (pull request) for this that changes the getter calls to real method calls but unfortunately that would break backwards compatibility.

So instead of calling `"example_string".camelize` one would have to use real method calls `"example_string".camelize()` even if no parameters are given.

Is this okay for you?

**Comment by pksunkara** [comment]
I would recommend using `inflect.camelize('message_properties', false)` form if anyone ever needs to pass that parameter.
