### ISSUE TITLE
undefined is not a function

### ISSUE THREAD

**Issue by adamski** [pksunkara/inflect#10]
I am getting the error ```TypeError: undefined is not a function``` when trying to use this package. Didn't have time to investigate but other packages are working fine for me.

**Comment by pksunkara** [comment]
Can you give me more details? The tests are passing as they should.

**Comment by pksunkara** [comment]
Can I get the stack trace?

**Comment by adamski** [comment]
Sure:
```
console.log(inflect.pluralize('apples'));
                    ^
TypeError: undefined is not a function
    at Object.<anonymous> (/path-to-my-app/server.js:34:21)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by pksunkara** [comment]
Are you sure you have initialised `inflect`? Can you give me that line in the code too?

**Comment by adamski** [comment]
yes its the standard 
```
var inflect = require('i');
```

**Comment by pksunkara** [comment]
I am afraid you are using it wrongly. From the README,

```
var inflect = require('i')();
```

**Comment by adamski** [comment]
aha sorry, I completely missed that. working great now, thanks!
