### ISSUE TITLE
0.3.2 version is not available on npm any more

### ISSUE THREAD

**Issue by aaronabramov** [pksunkara/inflect#11]
```
-> npm i i@0.3.2

npm ERR! Error: version not found: i@0.3.2
npm ERR! not ok code 0
```

It was previously there, because it's in my `npm-shrinkwrap.json`

```
-> npm v i
{ name: 'i',
  description: 'custom inflections for nodejs',
  'dist-tags':
   { latest: '0.3.3'},
  versions:
   [ '0.2.0',
     '0.3.0',
     '0.3.1',
     '0.3.3' ]
...
```

**Comment by pksunkara** [comment]
I am really sorry about this. I wanted to update the README and `npm` fucked me up by deleting `0.3.2` when I ran `npm publish -f` instead of telling me that the command doesn't work anymore.

Please update to 0.3.3

**Comment by pksunkara** [comment]
I am trying to get it published back again.

**Comment by dmitriiabramov** [comment]
:)
Thanks @pksunkara

**Comment by demands** [comment]
Thanks for trying to get this fixed!
It's bitten me too :(

**Comment by pksunkara** [comment]
Sorry guys. Npm people have said that they cannot do anything regarding this. Please update to 0.3.3 and tell any other people who might want to know.

**Comment by sketchman-nyt** [comment]
Same problem here! I was trying to figure out why our build pipeline failed and this seems to be it. We'll see about switching to 0.3.3 for now.

**Comment by sketchman-nyt** [comment]
I take that back, after removing our shrinkwrap and node_modules, it picked up 0.3.3, so all is good again.

**Comment by pksunkara** [comment]
From NPM guys,

> I'm sorry about this bug you've run afoul of, and I understand your frustration.
> 
> We discussed at work yesterday how to re-architect the CLI/registry to make this impossible in the future.
> 
> Unfortunately, we have no mechanism to publish a package over top of a prior version. npm is a distributed system, with information in redundant databases and hard-drives. The package version and name represents a unique identifier across these distributed systems, and cannot be modified.
> 
> We will take steps in the future to address this bug,

**Comment by nkbt** [comment]
@pksunkara I wonder, if it is possible to checkout particular revision  and then publish it to npm?

**Comment by pksunkara** [comment]
@nkbt I tried that. It wasn't working.

**Comment by fresheneesz** [comment]
I ran into this too - it would be great if you could publish *some* version on 0.3.2 (doesn't have to be the right one, 0.3.3 will do). But seeing this error has lost us a bunch of time.

**Comment by pksunkara** [comment]
@fresheneesz That is the problem. NPM is not letting me publish **anything** to 0.3.2

**Comment by fresheneesz** [comment]
http://blog.npmjs.org/post/77758351673/no-more-npm-publish-f : /

If you use `i` directly, change your version. If you've shrinkwrapped `i`, delete the shrinkwrap entries for i and re `npm install`

**Comment by marudhuri** [comment]
I am new to node and trying to run an existing application and it fails saying that 0.3.2 doesn't exist. 
Is there a way to figure out what is causing the i 0.3.2 does not exist? and fix it?  I dont see that listed in the package.json file. Please help.

**Comment by pksunkara** [comment]
@marudhuri It is probably required in one of the child node modules or is hardcoded in npm shrink-wrap.

**Comment by marudhuri** [comment]
I tried doing a "npm ls i" and I could not find any reference to 0.3.2 and I tried doing a "npm shrinkwrap" and the shrinkwrap json that got created does not show any 0.3.2. not sure what else I could do...

**Comment by marudhuri** [comment]
Thanks @pksunkara Pavan for quickly responding.I asked this on stackoverflow and Joey was able to help me there. See http://stackoverflow.com/questions/32463020/npm-err-version-not-found-i0-3-2-error.

**Comment by Multigence** [comment]
I'm unfortunately still struggling with this. It seems that on node v0.10.35 (npm v1.4.28) is not possible to workaround the problem when trying to install module `"keystone": "~0.2.27"`. Also tried upgrading and downgrading the version in package.json as well as trying a timid `"keystone": "^0.2.27"`. 

Anyway the chain is that keystone depend on keystone-utils@0.1.12
https://libraries.io/npm/keystone/0.2.27
but keystone-utils should depend on i@0.3.3
https://libraries.io/npm/keystone-utils/0.1.12

The fun part is that `npm install keystone@0.2.27` does not fail from terminal, but just when invoked by the package.json.

May this be caused by npm version? Does it make sense to upgrade npm under nvm? 

Tried node v0.12.x and failed on other libraries. So, I suppose I have to stick with a old npm.

**Comment by pksunkara** [comment]
@Multigence Maybe try clearing your npm cache? Or maybe you have conflicts in the project you are using keystone in.

**Comment by Multigence** [comment]
@pksunkara I solved the issue. Since I had inherited the code from another code, I didn't realize he had made a shrinkwrap which was exactly lacking those modules and citing i@0.3.2. Now everything works fine.
