### ISSUE TITLE
"Foe" special case

### ISSUE THREAD

**Issue by Pampattitude** [pksunkara/inflect#13]
Hi!

I think the word "foe" should be defined as a special case.

```javascript
console.log(i.pluralize('foe'));
// 'foes'
console.log(i.singularize('foes'));
// 'fo'
```

In the mean time though,
```javascript
i.inflections.singular('foes', 'foe');
```
is enough, but still!

Keep up the amazing work!

**Comment by pksunkara** [comment]
Please use `i.inflections.singular('foes', 'foe');`. I don't want to change this library for just adding special cases. Thanks for your understanding.
