### ISSUE TITLE
Incorrect rules in defaults (octopus, virus)

### ISSUE THREAD

**Issue by mdarens** [pksunkara/inflect#14]
[/lib/defaults.js](https://github.com/pksunkara/inflect/blob/master/lib/defaults.js#L7) has some rules which are grammatically incorrect.
See [the wiktionary entry on hypercorrection](https://en.wiktionary.org/wiki/Appendix:Glossary#hypercorrect) and [Plural form of words ending in -us](https://en.wikipedia.org/wiki/Plural_form_of_words_ending_in_-us)

**Comment by pksunkara** [comment]
I copied the rules from ruby on rails inflection module.
