### ISSUE TITLE
Trouble with cafe, loaf, fife

### ISSUE THREAD

**Issue by michaelrhanson** [pksunkara/inflect#17]
I noticed that the library was generating incorrect output for the special case cluster around trailing-F sounds.

The most obvious error is `cafe` to `caves`; more subtly, `fife` should be `fifes`, `safe` should be `safes` but `save` should be `saves`.

**Comment by michaelrhanson** [comment]
I created a PR to fix this issue:
https://github.com/pksunkara/inflect/pull/18

**Comment by pksunkara** [comment]
Fixed by 0.3.4
