### ISSUE TITLE
inflect.singularize('Address') returns 'Addres'

### ISSUE THREAD

**Issue by keithwhor** [pksunkara/inflect#20]
Similarly,

```
> inflect.singularize('dress')
'dres'
> inflect.singularize('mess')
'mes'
> inflect.singularize('loss')
'los'
> inflect.singularize('octopus')
'octopu'
```

I can spend some time looking through the codebase and submitting a PR if there's not an easily identifiable fix you can find?

Cheers,
- Keith

**Comment by pksunkara** [comment]
I would love it if you submit a PR. :)

**Comment by abossard** [comment]
I think the main problem is supplying a already singular word to singularize.

**Comment by pksunkara** [comment]
Hey @abossard. Yes, supplying a singular word to singularize is always going to be diffcult. So, if you have any issues you want to fix, You should use the custom stuff to do it as documented here. https://github.com/pksunkara/inflect#custom-irregular

This library was being used for a long time by a lot of people and I don't want to change for so small things and maybe even break things for some people.
