### ISSUE TITLE
titleize() changes non-alphanumerics to spaces

### ISSUE THREAD

**Issue by tawdle** [pksunkara/inflect#22]
```
inflect.titleize("sanford & sons") => "Sanford   Sons"
```

The offending line is https://github.com/pksunkara/inflect/blob/355009895db1bd8dcceaa687b53fe085fc873b88/lib/methods.js#L208 -- obviously one could simply add to the list of acceptable characters, but I'm not sure why the code is making this substitution in the first place.

**Comment by tawdle** [comment]
@pksunkara would you be willing to bump the version number to include this?

**Comment by pksunkara** [comment]
Done.
