### ISSUE TITLE
Pluralize error for Barista: Baristum should be Baristas

### ISSUE THREAD

**Issue by chrismcleod** [pksunkara/inflect#24]
Barista pluralizes to Baristum.  Though it's an Italian word, In English, the plural form should be Baristas.

(I know you know this, just citing my sources :)
source: https://en.wikipedia.org/wiki/Barista

Thank you for this great library.

**Comment by pksunkara** [comment]
Hey @chrismcleod 

You should use the custom stuff to do this as documented here. https://github.com/pksunkara/inflect#custom-irregular

This library was being used for a long time by a lot of people and I don't want to change for so small things and maybe even break things for some people.

**Comment by chrismcleod** [comment]
A very sympathetic decision 👍
