### ISSUE TITLE
webpack production icons not showing

### ISSUE THREAD

**Issue by rkoleci** [pksunkara/inflect#26]
{ test: /\.ico$/, loader: 'file?name=[name].[ext]' },

what do I need to include in the webpack config ?

**Comment by pksunkara** [comment]
Are you sure you are talking about this project?

Pavan Kumar Sunkara

**Comment by rkoleci** [comment]
Yes. I have installed this project and its on my dependencies "i": "^0.3.6", but what should I include in the webpack config (ignore my current webpack code; its probably wrong) ?

**Comment by pksunkara** [comment]
You don't need to include anything special for this dependency. This is just a normal node module.

**Comment by rkoleci** [comment]
It's working now. Thank you very much.
