### ISSUE TITLE
Audit vulnerabilities detected in the i project on Tag: v0.3.6

### ISSUE THREAD

**Issue by Mahir92** [pksunkara/inflect#33]
**Issue**: We detected vulnerable dependencies in your project by using the command “npm audit”:
#### npm audit report

diff  <3.5.0
Severity: high
Regular Expression Denial of Service - https://npmjs.com/advisories/1631
fix available via `npm audit fix --force`
Will install vows@0.8.3, which is a breaking change
node_modules/diff
  vows  0.6.4 - 0.8.2 || 0.9.0-rc1 - 0.9.0-rc3
  Depends on vulnerable versions of diff
  node_modules/vows

2 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

**Questions**: We are conducting a research study on vulnerable dependencies in open-source JS projects. We are curious:
1. Will you fix the vulnerabilities mentioned above? (Yes/No), and why?:
2. Do you have any additional comments? (If so, please write it down):

For any publication or research report based on this study, we will share all responses from developers in an anonymous way. Both your projects and personal information will be kept confidential.

**Description**: Many popular NPM packages have been found vulnerable and may carry significant risks [1]. Developers are recommended to monitor and avoid the vulnerable versions of the library. The vulnerabilities have been identified and reported by other developers, and their descriptions are available in the npm registry [2].

**Steps to reproduce**:
- Go to the root folder of the project where the package.json file located
- Execute “npm audit”
- Look at the list of vulnerabilities reported

**Suggested Solution**: Npm has introduced the “npm audit fix” command to fix the vulnerabilities. Execute the command to apply remediation to the dependency tree.

**References**:
2019. 10 npm Security Best Practices.  https://snyk.io/blog/ten-npm-security-best-practices/.
2021. npm-audit. https://docs.npmjs.com/cli/v7/commands/npm-audit.

**Comment by pksunkara** [comment]
First of all, `vows` is a dev dependency. Second of all, doing `npm audit` gave me 0 vulnerabilities on a fresh node_modules folder.
